'use client'
import {useEffect,useRef,useState} from 'react';import {createClient} from '@/lib/supabase/client'
type SignupData={phone_number_id?:string;waba_id?:string;business_id?:string};type FbResponse={authResponse?:{code?:string};status?:string};type FbApi={init:(options:Record<string,unknown>)=>void;login:(callback:(response:FbResponse)=>void,options:Record<string,unknown>)=>void}
declare global{interface Window{FB?:FbApi;fbAsyncInit?:()=>void}}
export function MetaEmbeddedSignup({tenantId,onConnected}:{tenantId:string;onConnected?:()=>void}){const appId=process.env.NEXT_PUBLIC_META_APP_ID||'';const configId=process.env.NEXT_PUBLIC_META_CONFIG_ID||'';const[ready,setReady]=useState(false);const[loading,setLoading]=useState(false);const[message,setMessage]=useState('');const[error,setError]=useState('');const codeRef=useRef('');const sessionRef=useRef<SignupData>({});const completing=useRef(false);const configured=Boolean(appId&&configId)
async function complete(){if(completing.current||!codeRef.current||!sessionRef.current.phone_number_id||!sessionRef.current.waba_id)return;completing.current=true;setLoading(true);const{data,error:fnError}=await createClient().functions.invoke('whatsapp-embedded-signup',{body:{tenant_id:tenantId,code:codeRef.current,phone_number_id:sessionRef.current.phone_number_id,waba_id:sessionRef.current.waba_id,business_id:sessionRef.current.business_id||null}});setLoading(false);completing.current=false;if(fnError||data?.error){setError(data?.message||data?.meta_error||fnError?.message||'Não foi possível concluir a conexão.');return}setMessage('WhatsApp Business conectado com sucesso.');setError('');onConnected?.()}
useEffect(()=>{if(!configured)return;const listener=(event:MessageEvent)=>{try{const host=new URL(event.origin).hostname;if(host!=='facebook.com'&&!host.endsWith('.facebook.com'))return;const payload=typeof event.data==='string'?JSON.parse(event.data):event.data;if(payload?.type!=='WA_EMBEDDED_SIGNUP')return;if(payload.event==='FINISH'){sessionRef.current=payload.data||{};void complete()}else if(payload.event==='CANCEL'){setError('Conexão cancelada antes de concluir.');setLoading(false)}else if(payload.event==='ERROR'){setError(payload.data?.error_message||'A Meta retornou um erro no Embedded Signup.');setLoading(false)}}catch{}};window.addEventListener('message',listener);window.fbAsyncInit=()=>{window.FB?.init({appId,autoLogAppEvents:true,xfbml:false,version:'v25.0'});setReady(true)};if(window.FB){window.fbAsyncInit()}else if(!document.getElementById('facebook-jssdk')){const script=document.createElement('script');script.id='facebook-jssdk';script.async=true;script.defer=true;script.crossOrigin='anonymous';script.src='https://connect.facebook.net/pt_BR/sdk.js';document.body.appendChild(script)}return()=>window.removeEventListener('message',listener)},[appId,configured])
function launch(){setError('');setMessage('');if(!configured){setError('Faltam NEXT_PUBLIC_META_APP_ID e NEXT_PUBLIC_META_CONFIG_ID.');return}if(!window.FB||!ready){setError('O SDK da Meta ainda está carregando. Tente novamente em instantes.');return}setLoading(true);sessionRef.current={};codeRef.current='';window.FB.login(response=>{const code=response.authResponse?.code||'';if(!code){setLoading(false);setError('A autorização da Meta não foi concluída.');return}codeRef.current=code;void complete()},{config_id:configId,response_type:'code',override_default_response_type:true,extras:{setup:{},featureType:'',sessionInfoVersion:'3'}})}
return <div><button type="button" className="btn btn-primary" onClick={launch} disabled={loading||(!ready&&configured)}>{loading?'Conectando…':'Conectar com WhatsApp'}</button>{!configured&&<div className="embedded-status">Embedded Signup pronto no código. Falta cadastrar App ID e Configuration ID da Meta.</div>}{message&&<div className="success-box" style={{marginTop:12}}>{message}</div>}{error&&<div className="error-box" style={{marginTop:12}}>{error}</div>}</div>}
